# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0847ec3919f8940931a98d1e9993fbe995b6cf5390444b510da89577ba0068073c7cf7e8b961714884cfb65a295837262a80fdd6a3c15dd66cfe012ff60ab3b1

test:
  secret_key_base: 6bdb0ce9e7fb22a60776387d71a59178e8a0cd19c2d81f23fa662c333645a035a7a9c562538ae49e9a0615c45ecfbd3cc50dfa31fed2a10a039edafcba99568e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
